describe("Custom augment backports", function()
	it("recognizes Xopec and applies its magnitude through the normal item and Shock pipeline", function()
		dofile("../tests/custom_augments.lua")
	end)
	it("supports the remaining 0.5.5 cores and equipped limits", function()
		dofile("../tests/custom_augments_055.lua")
	end)
end)
